# Generated by Django 2.1.5 on 2019-01-07 03:09

from django.db import migrations, models
import tweet.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=140, validators=[tweet.validators.validate_content]),
        ),
    ]
